name: Metrics

on:
  schedule: [{cron: "0 */4 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          base_indepth: true
          repositories_forks: true

          plugin_languages: true
          plugin_languages_indepth: true
          plugin_languages_other: false
          plugin_languages_analysis_timeout: 60
          plugin_languages_analysis_timeout_repositories: 15
          plugin_languages_details: lines

          plugin_isocalendar: true

          plugin_activity: true
          plugin_activity_limit: 5

          plugin_achievements: true
          plugin_achievements_display: compact

          config_display: large

          output_action: gist
          committer_gist: dc04e4cbe43458f0c44436bf851672ee
